-  name: Install catalogue component
   hosts: catalogue
   become: yes
   tasks:
   -  name: setup NPM Source
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
   -  name: Install NodeJS
      ansible.builtin.yum:
       name: nodejs 
       state: installed

   -  name: check user is present or not
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true
   -  when: out.rc != 0
      name: create user roboshop
      become: yes
      ansible.builtin.user: 
       name: roboshop

   -  name: check /app directory is present or not
      ansible.builin.stat: 
       path: /app
      register: output
      ignore_errors: true

   -  when: output.stat.exists == False
      ansible.builtin.file:
       path: /app
       state: directory
   -  name: download catalogue artifact
      ansible.builtin.url: 
        url: curl -o /tmp/catalogue.zip https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp
   -  name: extract catalogue artifact
      ansible.builtin.unarchive :
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
   -  name: install dependencies
      ansible.builtin.command: npm install
      args:
       chdir:/app