-  name: Install rabbitmq
   hosts: rabbitmq
   become: yes
   tasks:
   - name: Configure rabbitmq yum repo
     ansible.builtin.shell: "{{item}}"
     loop: 
     - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
     - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

   - name: Install rabbitmq 
     ansible.builtin.yum:
      name: rabbitmq-server
      state: intalled

   - name: start and enable rabbitmq server
     ansible.builtin.service:
      name: rabbitmq-server
      state: restarted
      enabled: true
     
   - name: create rabbitmq user
     ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123


   - name: change permissions
     ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"